name: Create documentation and push to gh-pages

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make_docs:
    name: Create and push docs (${{ github.ref_name }})
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.ref_name }}
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install packages
        run: |
          python -m pip install .[pyterrier] pdoc
      - name: Check out gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Remove old files
        run: |
          rm -rf docs/${{ github.ref_name }}
          rm -f docs/index.html
      - name: Run pdoc
        run: |
          pdoc fast_forward -d google -o docs/${{ github.ref_name }}
      - name: Generate directory listing
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: .
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          destination_dir: docs
